<!DOCTYPE html>
<html>
<head>
    <title>Sales vs Purchase Performance Report</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10px; color: #333; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #4361ee; padding-bottom: 10px; }
        .report-title { font-size: 18px; font-weight: bold; color: #4361ee; margin-bottom: 5px; }
        .period { font-size: 12px; color: #666; }
        
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 8px; text-align: left; font-size: 9px; text-transform: uppercase; color: #64748b; }
        td { border: 1px solid #e2e8f0; padding: 8px; vertical-align: top; }
        
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .fw-bold { font-weight: bold; }
        .text-success { color: #10b981; }
        .text-danger { color: #ef4444; }
        
        .summary-box { margin-top: 30px; width: 100%; border-top: 2px solid #eee; padding-top: 15px; }
        .summary-item { display: inline-block; width: 32%; text-align: center; }
        .summary-label { font-size: 9px; color: #64748b; text-transform: uppercase; margin-bottom: 5px; }
        .summary-value { font-size: 14px; font-weight: bold; }
        
        .footer { position: fixed; bottom: 0; width: 100%; font-size: 8px; color: #94a3b8; text-align: right; padding-top: 10px; border-top: 1px solid #eee; }
    </style>
</head>
<body>
    <div class="header">
        <div class="report-title">Sales vs Purchase Performance ({{ ($groupBy ?? 'variation') === 'product' ? 'Style-Wise' : 'Size-Wise' }})</div>
        <div class="period">Period: {{ $startDate->format('d M Y') }} - {{ $endDate->format('d M Y') }}</div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Product Details</th>
                <th class="text-center">Sold</th>
                <th class="text-center">Ret</th>
                <th class="text-center">Net</th>
                <th class="text-right">Net Sale (৳)</th>
                <th class="text-right">Net Cost (৳)</th>
                <th class="text-right">Profit (৳)</th>
                <th class="text-center">Margin</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data as $index => $item)
                <tr>
                    <td class="text-center">{{ $index + 1 }}</td>
                    <td>
                        <div class="fw-bold">{{ $item->product_name }}</div>
                        <div style="font-size: 8px; color: #666;">Style: {{ $item->style_number }} | {{ ($groupBy ?? 'variation') === 'product' ? 'Details' : 'Variation' }}: {{ $item->variation_name }}</div>
                    </td>
                    <td class="text-center">{{ $item->sold_qty }}</td>
                    <td class="text-center text-danger">{{ $item->returned_qty }}</td>
                    <td class="text-center fw-bold">{{ $item->net_qty }}</td>
                    <td class="text-right fw-bold">{{ number_format($item->net_sale_amount, 2) }}</td>
                    <td class="text-right text-muted">{{ number_format($item->net_purchase_cost, 2) }}</td>
                    <td class="text-right">
                        <span class="{{ $item->gross_profit >= 0 ? 'text-success' : 'text-danger' }} fw-bold">
                            {{ number_format($item->gross_profit, 2) }}
                        </span>
                    </td>
                    <td class="text-center">
                        <span class="{{ $item->profit_margin >= 0 ? 'text-success' : 'text-danger' }}">
                            {{ number_format($item->profit_margin, 2) }}%
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary-box">
        <div class="summary-item">
            <div class="summary-label">Total Net Revenue</div>
            <div class="summary-value">৳ {{ number_format($summary['total_sale'], 2) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Total Purchase Cost</div>
            <div class="summary-value">৳ {{ number_format($summary['total_cost'], 2) }}</div>
        </div>
        <div class="summary-item">
            <div class="summary-label">Total Gross Profit</div>
            <div class="summary-value">৳ {{ number_format($summary['total_profit'], 2) }}</div>
        </div>
    </div>

    <div class="footer">
        Generated by ERP System on {{ date('d M Y H:i A') }} | Page 1
    </div>
</body>
</html>
